#!/bin/bash
echo "========== V10训练（优化前）=========="
echo "准确率波动: 33.3% - 70.8%"
echo "平均: ~54.5%"
echo "主要问题:"
echo "  - 代码块提取失败"
echo "  - QA选项匹配失败"
echo "  - Workflow AttributeError"
echo ""
echo "========== 当前训练（优化后）=========="
echo "进程ID: 3ef748"
echo "WandB: https://wandb.ai/yao110002-sdfsdfsdfsdf-com/agent-prompt/runs/uemsdcvd"
echo ""
echo "最新准确率:"
tail -20 wandb/run-20251123_185855-uemsdcvd/logs/debug-internal.log 2>/dev/null | grep -E '准确率|正确性评分' | tail -5 || echo "等待更多数据..."
